### ISSUE TITLE
warpPerspective parameter mistake

### ISSUE THREAD

**Issue by narrowsnap** [ruc-aimc-lab/SuperRetina#1]
There is a mistake in notebooks/tutorial-inference.ipynb.

<img width="1103" alt="Screenshot_2022-12-06_at_16_54_45" src="https://user-images.githubusercontent.com/17559987/205866804-7a775755-3690-4eb0-8f41-f133c712ea93.png">

Here the parameters are reversed. It should be (w, h).

**Comment by jiazhen-code** [comment]
Hi, @narrowsnap, many thanks for pointing this out! 
Since the height and width of our test images are the same, this mistake doesn't influence the performance reported in the paper. We've fixed this in commit [8fbfd8b](https://github.com/ruc-aimc-lab/SuperRetina/commit/8fbfd8ba4d0f0aa61ea8080ad3ebd9f9b2b262b3).
